name: _ reusable build workflow

on:
  workflow_call:
    inputs:
      subdirectory:
        description: "Subdirectory to run the build in"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Remove `refs/tags/$component-` from tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "TAG=${GITHUB_REF/refs\/tags\/$COMPONENT-/}" >> $GITHUB_ENV
        env:
          GITHUB_REF: ${{ github.ref }}
          COMPONENT: ${{ inputs.subdirectory }}

      - name: Generate image metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}/${{ inputs.subdirectory }}
          tags: |
            # branch tags
            type=ref,event=branch
            type=ref,event=pr

            # release tags
            type=semver,pattern={{version}},enable=${{ startsWith(github.ref, 'refs/tags/') }},value=${{ env.TAG }}
            type=semver,pattern={{major}}.{{minor}},enable=${{ startsWith(github.ref, 'refs/tags/') }},value=${{ env.TAG }}
            type=semver,pattern={{major}},enable=${{ startsWith(github.ref, 'refs/tags/') }},value=${{ env.TAG }}

            # always fallback to sha
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ${{ inputs.subdirectory }}
          file: ${{ inputs.subdirectory }}/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
