name: Build Image B

on:
  push:
    tags:
      - 'image-b-v*'
  pull_request:
    branches:
      - main
    paths:
      - 'image-b/**'

jobs:
  build:
    uses: ./.github/workflows/_build.yaml
    secrets: inherit
    with:
      subdirectory: image-b
