name: Build Image A

on:
  push:
    tags:
      - 'image-a-v*'
  pull_request:
    branches:
      - main
    paths:
      - 'image-a/**'

jobs:
  build:
    uses: ./.github/workflows/_build.yaml
    secrets: inherit
    with:
      subdirectory: image-a
